version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wp_network
    restart: unless-stopped

  php:
    image: wordpress:php8.2-fpm
    container_name: php_fpm
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wp_network
    depends_on:
      - db
    restart: unless-stopped


  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wp_network
    depends_on:
      - php
    restart: unless-stopped

# monitorung
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "9100:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - wp_network
    restart: unless-stopped

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld-exporter
    ports:
      - "9104:9104"
    environment:
      DATA_SOURCE_NAME: "wpuser:wppass@(db:3306)/wordpress"
    command:
      - "--mysqld.username=wpuser:wppass"
      - "--mysqld.address=db:3306"
    networks:
      - wp_network
    depends_on:
      - db
    restart: unless-stopped

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command:
      - '-nginx.scrape-uri=http://nginx:80/nginx_status'
    ports:
      - "9113:9113"
    networks:
      - wp_network
    depends_on:
      - nginx
    restart: unless-stopped

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    networks:
      - wp_network
    restart: unless-stopped
    
  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    ports:
      - "9009:9009"
    volumes:
      - ./mimir.yml:/etc/mimir/mimir.yaml
    command: --config.file=/etc/mimir/mimir.yaml
    networks:
      - wp_network
    restart: unless-stopped


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - wp_network
    depends_on:
      - node-exporter
      - mysqld-exporter
      - nginx-exporter
      - blackbox-exporter
      - mimir
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--log.level=debug"
      
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - wp_network
    depends_on:
      - mimir
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  mysql_data:
  grafana-storage:

networks:
  wp_network:
    driver: bridge
